version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - asciicheck
    - asasalint
    - dogsled
    - dupword
    - durationcheck
    - errname
    - errcheck
    - errchkjson
    - exhaustive
    - forcetypeassert
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errorlint
    - bodyclose
    - bidichk
    - gocheckcompilerdirectives
    - gocritic
    - gocyclo
    - misspell
    - makezero
    - nilerr
    - nilnil
    - usestdlibvars
    - unconvert
    - prealloc
    - predeclared
    - nolintlint
    - wastedassign
    - unparam

  settings:
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-checks:
        - boolExprSimplify
        - emptyStringTest
        - evalOrder
        - octalLiteral
        - rangeValCopy
        - whyNoLint
    misspell:
      locale: US

formatters:
  enable:
    - gofumpt

issues:
  exclude-use-default: false
